services:
  - type: web
    name: freefire-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
